# Generated by Django 6.0 on 2025-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='active_config',
            field=models.TextField(blank=True, help_text='Configuración JSON activa para la generación. Se rellena desde el panel de configuración.', null=True),
        ),
    ]
