# Generated by Django 6.0 on 2025-12-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_workflow_active_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('character_config', models.TextField(blank=True, help_text='Configuración JSON específica para este personaje.', null=True)),
                ('base_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='myapp.workflow')),
            ],
        ),
    ]
