# Generated by Django 6.0 on 2025-12-17 05:30

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myapp.models.character_image_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.character')),
            ],
        ),
    ]
