# Generated by Django 6.0 on 2025-12-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_characterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='is_user_generated',
            field=models.BooleanField(default=False),
        ),
    ]
