# Generated by Django 6.0 on 2025-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_characterimage_is_user_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
