# Generated by Django 6.0 on 2025-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_characterimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Local, GPU Empresa', max_length=100)),
                ('base_url', models.CharField(help_text='Ej: http://127.0.0.1:8188 o https://tu-url.trycloudflare.com', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Marca esta casilla para usar esta conexión.')),
            ],
            options={
                'verbose_name': 'Configuración de Conexión',
                'verbose_name_plural': 'Configuraciones de Conexión',
            },
        ),
        migrations.RemoveField(
            model_name='characterimage',
            name='is_user_generated',
        ),
        migrations.AlterField(
            model_name='characterimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
