# Generated by Django 6.0 on 2025-12-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_connectionconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='negative_prompt',
            field=models.TextField(blank=True, default='ugly, deformed, noisy, blurry, low contrast, text, watermark, extra limbs, extra fingers', help_text='Cosas que NO quieres en la imagen (ej: deformidades, texto, etc).', null=True),
        ),
    ]
