# Generated by Django 6.0 on 2025-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_character_negative_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='positive_prompt',
            field=models.TextField(blank=True, default='masterpiece, best quality, ultra-detailed, 8k', help_text='Cosas que SIEMPRE quieres en la imagen (ej: obra maestra, mejor calidad).', null=True),
        ),
    ]
