# Generated by Django 6.0 on 2025-12-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_characterimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
