# Generated by Django 6.0 on 2025-12-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_character_prompt_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción interna del personaje, notas sobre su estilo, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='negative_prompt',
            field=models.TextField(blank=True, default='score_6, score_5, score_4, source_cartoon, 3d, illustration, (worst quality, low quality:1.2), deformed, bad anatomy', help_text='NEGATIVO: Cosas que NO quieres en la imagen.', null=True, verbose_name='Prompt Negativo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='positive_prompt',
            field=models.TextField(blank=True, default='1girl, solo, beautiful woman, detailed skin', help_text='SUFIJO: Va DESPUÉS del prompt del usuario. Úsalo para describir al personaje (pelo, ojos, cuerpo).', null=True, verbose_name='Prompt Sufijo (Identidad)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='prompt_prefix',
            field=models.TextField(blank=True, default='score_9, score_8_up, score_7_up, score_6_up, source_anime, rating_explicit, (masterpiece, best quality)', help_text='PREFIJO: Va ANTES del prompt del usuario. Úsalo para Quality Tags (score_9...) y estilo.', null=True, verbose_name='Prompt Prefijo (Calidad)'),
        ),
    ]
