# Generated by Django 6.0 on 2025-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_character_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='app_hero_description',
            field=models.TextField(blank=True, default='Transforma tus ideas en arte con nuestro potente motor de IA. Crea personajes únicos en segundos.', help_text='El texto descriptivo debajo del título principal.', verbose_name='Descripción Principal (Hero)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='app_hero_title',
            field=models.CharField(default='Generador Anime - Realista', help_text='El título grande que aparece en la página principal.', max_length=200, verbose_name='Título Principal (Hero)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción (Footer)'),
        ),
    ]
