# Generated by Django 6.0 on 2025-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_companysettings_app_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='hero_images',
            field=models.ManyToManyField(blank=True, help_text="Selecciona hasta 15 imágenes. Solo aplica si el modo es 'Manual'.", limit_choices_to={'user__isnull': True}, to='myapp.characterimage', verbose_name='Imágenes del Carrusel'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='hero_mode',
            field=models.CharField(choices=[('random', 'Aleatorio (Automático)'), ('manual', 'Manual (Seleccionado)')], default='random', max_length=10, verbose_name='Modo del Carrusel'),
        ),
    ]
