# Generated by Django 6.0 on 2025-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_companysettings_hero_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='hero_images',
            field=models.ManyToManyField(blank=True, help_text="Selecciona hasta 15 imágenes. Solo aplica si el modo es 'Manual'.", limit_choices_to=models.Q(('user__isnull', True), ('user__is_staff', True), _connector='OR'), to='myapp.characterimage', verbose_name='Imágenes del Carrusel'),
        ),
    ]
