# Generated by Django 6.0 on 2025-12-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_companysettings_hero_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='hero_images',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='hero_characters',
            field=models.ManyToManyField(blank=True, help_text='Selecciona hasta 6 personajes. Se mostrará la primera imagen disponible de cada uno.', to='myapp.character', verbose_name='Personajes del Carrusel'),
        ),
    ]
