# Generated by Django 6.0 on 2025-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_count',
            field=models.IntegerField(default=0, help_text='Número de imágenes generadas originalmente en este mensaje.'),
        ),
    ]
