# Generated by Django 6.0 on 2025-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_chatmessage_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
