# Generated by Django 6.0 on 2025-12-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_characterimage_height_characterimage_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='offer_bar_text',
            field=models.CharField(blank=True, help_text="Texto que aparece en la barra superior (ej: '🎉 ¡Oferta Especial!'). Déjalo vacío para ocultar la barra.", max_length=255, null=True, verbose_name='Texto Barra de Oferta'),
        ),
    ]
