# Generated by Django 6.0 on 2026-01-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_companysettings_offer_bar_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Company Settings', 'verbose_name_plural': 'Company Settings'},
        ),
        migrations.AlterModelOptions(
            name='connectionconfig',
            options={'verbose_name': 'Connection Configuration', 'verbose_name_plural': 'Connection Configurations'},
        ),
        migrations.AddField(
            model_name='characterimage',
            name='is_showcase',
            field=models.BooleanField(default=False, help_text='Check this box to show this image in the public catalog (Max 4 per character).', verbose_name='Show in Catalog'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_config',
            field=models.TextField(blank=True, help_text='Specific JSON configuration for this character.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, help_text='Internal character description, style notes, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='negative_prompt',
            field=models.TextField(blank=True, default='score_6, score_5, score_4, source_cartoon, 3d, illustration, (worst quality, low quality:1.2), deformed, bad anatomy', help_text='NEGATIVE: Things you DO NOT want in the image.', null=True, verbose_name='Negative Prompt'),
        ),
        migrations.AlterField(
            model_name='character',
            name='positive_prompt',
            field=models.TextField(blank=True, default='1girl, solo, beautiful woman, detailed skin', help_text='SUFFIX: Goes AFTER the user prompt. Use to describe the character (hair, eyes, body).', null=True, verbose_name='Prompt Suffix (Identity)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='prompt_prefix',
            field=models.TextField(blank=True, default='score_9, score_8_up, score_7_up, score_6_up, source_anime, rating_explicit, (masterpiece, best quality)', help_text='PREFIX: Goes BEFORE the user prompt. Use for Quality Tags (score_9...) and style.', null=True, verbose_name='Prompt Prefix (Quality)'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image_count',
            field=models.IntegerField(default=0, help_text='Number of images originally generated in this message.'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='app_hero_description',
            field=models.TextField(blank=True, default='Transform your ideas into art with our powerful AI engine. Create unique characters in seconds.', help_text='The descriptive text below the main title.', verbose_name='Main Description (Hero)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='app_hero_title',
            field=models.CharField(default='Anime - Realistic Generator', help_text='The large title appearing on the main page.', max_length=200, verbose_name='Main Title (Hero)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description (Footer)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='hero_characters',
            field=models.ManyToManyField(blank=True, help_text='Select up to 6 characters. The first available image of each will be shown.', to='myapp.character', verbose_name='Carousel Characters'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='hero_mode',
            field=models.CharField(choices=[('random', 'Random (Automatic)'), ('manual', 'Manual (Selected)')], default='random', max_length=10, verbose_name='Carousel Mode'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(default='My Company', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='offer_bar_text',
            field=models.CharField(blank=True, help_text="Text appearing in the top bar (e.g., '🎉 Special Offer!'). Leave empty to hide.", max_length=255, null=True, verbose_name='Offer Bar Text'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='connectionconfig',
            name='base_url',
            field=models.CharField(help_text='Ex: http://127.0.0.1:8188 or https://your-url.trycloudflare.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check this box to use this connection.'),
        ),
        migrations.AlterField(
            model_name='connectionconfig',
            name='name',
            field=models.CharField(help_text='Ex: Local, Company GPU', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='active_config',
            field=models.TextField(blank=True, help_text='Active JSON configuration for generation. Filled from the configuration panel.', null=True),
        ),
    ]
