# Generated by Django 6.0 on 2026-01-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterimage',
            name='is_showcase',
        ),
        migrations.AddField(
            model_name='character',
            name='catalog_images',
            field=models.ManyToManyField(blank=True, help_text='Select up to 4 images to display in the public catalog/carousel.', related_name='featured_in_character', to='myapp.characterimage', verbose_name='Catalog Images'),
        ),
    ]
