# Generated by Django 6.0 on 2026-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_characterimage_is_showcase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='catalog_images',
            field=models.ManyToManyField(blank=True, help_text='Select images to display in the public catalog/carousel.', related_name='featured_in_character', to='myapp.characterimage', verbose_name='Catalog Images'),
        ),
    ]
