# Generated by Django 6.0 on 2026-01-02 06:36

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_character_catalog_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='catalog_images',
        ),
        migrations.CreateModel(
            name='CharacterCatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myapp.models.character_catalog_path)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the carousel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_images_set', to='myapp.character')),
            ],
            options={
                'verbose_name': 'Catalog Image',
                'verbose_name_plural': 'Catalog Images',
                'ordering': ['order'],
            },
        ),
    ]
