# Generated by Django 6.0 on 2026-01-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_character_catalog_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='hero_characters',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='hero_mode',
        ),
        migrations.CreateModel(
            name='HeroCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_carousel/', verbose_name='Carousel Image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Caption (Optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the carousel')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='myapp.companysettings')),
            ],
            options={
                'verbose_name': 'Hero Carousel Image',
                'verbose_name_plural': 'Hero Carousel Images',
                'ordering': ['order'],
            },
        ),
    ]
