# Generated by Django 6.0 on 2026-01-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_companysettings_hero_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='positive_prompt',
        ),
        migrations.AddField(
            model_name='character',
            name='prompt_suffix',
            field=models.TextField(blank=True, default='score_9, score_8_up, score_7_up, score_6_up, source_anime, rating_explicit, (masterpiece, best quality)', help_text='SUFFIX: Goes AFTER the user prompt. Use for Quality Tags (score_9...) and style.', null=True, verbose_name='Prompt Suffix (Quality)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='prompt_prefix',
            field=models.TextField(blank=True, default='1girl, solo, beautiful woman, detailed skin', help_text='PREFIX: Goes BEFORE the user prompt. Use to describe the character (hair, eyes, body).', null=True, verbose_name='Prompt Prefix (Character)'),
        ),
    ]
