# Generated by Django 6.0 on 2026-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_character_positive_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a small square image (e.g., 32x32 or 192x192 png/ico) for the browser tab.', null=True, upload_to='company_logos/', verbose_name='Favicon'),
        ),
    ]
