# Generated by Django 6.0 on 2026-01-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_companysettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('REALISTIC', 'Realistic'), ('ANIME', 'Anime'), ('OTHER', 'Other')], default='OTHER', help_text='Category for filtering in the catalog.', max_length=20),
        ),
    ]
