# Generated by Django 6.0 on 2026-01-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_character_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'General Category',
                'verbose_name_plural': 'General Categories',
            },
        ),
        migrations.CreateModel(
            name='CharacterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Character Tag',
                'verbose_name_plural': 'Character Tags',
            },
        ),
        # CAMBIO CRÍTICO: Eliminar el campo antiguo y crear uno nuevo para evitar error de conversión
        migrations.RemoveField(
            model_name='character',
            name='category',
        ),
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.ForeignKey(help_text='Mandatory: The main classification (e.g., Realistic, Anime).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactercategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional: Secondary tags (e.g., Hero, Villain, Cyberpunk).', related_name='characters', to='myapp.charactertag'),
        ),
    ]
