# Generated by Django 6.0 on 2026-01-05 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_charactercategory_charactertag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='SubCategory Name')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='tags',
        ),
        migrations.AddField(
            model_name='character',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional: A specific sub-classification (e.g., Cyberpunk, Fantasy). Only one allowed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactersubcategory'),
        ),
        migrations.DeleteModel(
            name='CharacterTag',
        ),
    ]
