# Generated by Django 6.0 on 2026-01-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_charactersubcategory_remove_character_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='generation_type',
            field=models.CharField(choices=[('Gen_Normal', 'Normal'), ('Gen_UpScaler', 'Upscaler'), ('Gen_FaceDetailer', 'Face Detailer')], default='Gen_Normal', max_length=20, verbose_name='Generation Type'),
        ),
    ]
