# Generated by Django 6.0 on 2026-01-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_token_allowance', models.PositiveIntegerField(default=100, help_text='Default tokens assigned to all clients on reset.')),
                ('reset_interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Never')], default='MONTHLY', help_text='How often tokens are reset for all clients.', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='reset_interval',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='token_allowance',
        ),
    ]
