# Generated by Django 6.0 on 2026-01-05 04:32

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_tokensettings_remove_clientprofile_reset_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='generation_workflow',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.character_workflow_path, verbose_name='Generation Workflow (JSON)'),
        ),
    ]
