# Generated by Django 6.0 on 2026-01-06 06:41

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_characterimage_generation_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bonus_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Extra tokens granted via coupons or admin.'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=myapp.models.generate_coupon_code, editable=False, max_length=20, unique=True)),
                ('tokens', models.PositiveIntegerField(verbose_name='Tokens to Grant')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
