# Generated by Django 6.0 on 2026-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_clientprofile_bonus_tokens_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, this character will be hidden from the workspace.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='character',
            name='negative_prompt',
            field=models.TextField(blank=True, default='bad anatomy, bad hands, multiple views, abstract, signature, furry, anthro, 2koma, 4koma, comic, (text, watermark), logo, artist signature, patreon logo, patreon username, twitter username, blurred, unfocused, foggy, poorly drawn hands, poorly drawn fingers, bad quality, worst quality, worst detail,', help_text='NEGATIVE: Things you DO NOT want in the image.', null=True, verbose_name='Negative Prompt'),
        ),
        migrations.AlterField(
            model_name='character',
            name='prompt_prefix',
            field=models.TextField(blank=True, default='', help_text='PREFIX: Goes BEFORE the user prompt. Use to describe the character (hair, eyes, body).', null=True, verbose_name='Prompt Prefix (Character)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='prompt_suffix',
            field=models.TextField(blank=True, default='masterpiece, best quality, newest, absurdres, highres, anime coloring,', help_text='SUFFIX: Goes AFTER the user prompt. Use for Quality Tags (score_9...) and style.', null=True, verbose_name='Prompt Suffix (Quality)'),
        ),
    ]
