# Generated by Django 6.0 on 2026-01-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_adminuser_options_alter_clientuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='app_hero_subtitle',
            field=models.CharField(blank=True, help_text='A smaller title below the main one, but above the description.', max_length=255, null=True, verbose_name='Main Subtitle (Hero)'),
        ),
    ]
