# Generated by Django 6.0 on 2026-01-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_companysettings_app_hero_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='accent_glow_color',
            field=models.CharField(default='#ef4444', help_text='Hex code (e.g., #ef4444). Used for shadows and glows.', max_length=7, verbose_name='Accent Glow Color'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color_end',
            field=models.CharField(default='#ff9068', help_text='Hex code (e.g., #ff9068). Ends the gradient (Bottom-Right).', max_length=7, verbose_name='Gradient End Color'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color_mid',
            field=models.CharField(default='#ef4444', help_text='Hex code (e.g., #ef4444). Middle of the gradient.', max_length=7, verbose_name='Gradient Middle Color'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color_start',
            field=models.CharField(default='#a855f7', help_text='Hex code (e.g., #a855f7). Starts the gradient (Top-Left).', max_length=7, verbose_name='Gradient Start Color'),
        ),
    ]
