# Generated by Django 6.0 on 2026-01-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_companysettings_accent_glow_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='offer_bar_color',
            field=models.CharField(default='#10b981', help_text='Hex code (e.g., #10b981). Base color for the offer bar.', max_length=7, verbose_name='Offer Bar Color'),
        ),
    ]
