# Generated by Django 6.0 on 2026-01-16 06:43

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_companysettings_offer_bar_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCharacter',
            fields=[
            ],
            options={
                'verbose_name': 'Private Character',
                'verbose_name_plural': 'Private Characters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.character',),
        ),
        migrations.AddField(
            model_name='character',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, this character will NOT appear in the public list. Users need a code to access it.', verbose_name='Private Character'),
        ),
        migrations.CreateModel(
            name='CharacterAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=myapp.models.generate_coupon_code, help_text='Code to unlock the character.', max_length=20, unique=True)),
                ('limit_amount', models.PositiveIntegerField(default=50, help_text='How many images can be generated per interval.')),
                ('reset_interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Lifetime/One-time')], default='MONTHLY', help_text='How often the limit resets.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(limit_choices_to={'is_private': True}, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='myapp.character')),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_generated_current_period', models.PositiveIntegerField(default=0)),
                ('limit_amount', models.PositiveIntegerField(default=50)),
                ('reset_interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Lifetime/One-time')], default='MONTHLY', max_length=10)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.character')),
                ('source_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.characteraccesscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Private Character Access',
                'verbose_name_plural': 'User Private Character Accesses',
                'unique_together': {('user', 'character')},
            },
        ),
    ]
