# Generated by Django 6.0 on 2026-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_privatecharacter_character_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraccesscode',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of users who can redeem this code. Leave empty for infinite.', null=True, verbose_name='Max Users'),
        ),
        migrations.AddField(
            model_name='characteraccesscode',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Redeemed Count'),
        ),
        migrations.AlterField(
            model_name='characteraccesscode',
            name='code',
            field=models.CharField(blank=True, help_text='Code to unlock the character. Leave empty to auto-generate.', max_length=20, unique=True),
        ),
    ]
