# Generated by Django 6.0 on 2026-01-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_characteraccesscode_max_redemptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraccesscode',
            name='character',
            field=models.OneToOneField(limit_choices_to={'is_private': True}, on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='myapp.character'),
        ),
    ]
