# Generated by Django 6.0 on 2026-01-16 08:01

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_characteraccesscode_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_redeemed',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redeemed_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redeemed_by',
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of users who can redeem this coupon. Leave empty for infinite.', null=True, verbose_name='Max Users'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Redeemed Count'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=myapp.models.generate_coupon_code, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='myapp.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupon Redemptions',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
