# Generated by Django 6.0 on 2026-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_coupon_is_redeemed_remove_coupon_redeemed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='generation_type',
            field=models.CharField(choices=[('Gen_Normal', 'Normal'), ('Gen_UpScaler', 'Upscaler'), ('Gen_FaceDetailer', 'Face Detailer'), ('Gen_EyeDetailer', 'Eye Detailer')], default='Gen_Normal', max_length=20, verbose_name='Generation Type'),
        ),
    ]
