# Generated by Django 6.0 on 2026-01-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_characterimage_generation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auth_backgrounds/', verbose_name='Auth Background Image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Caption (Optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the slideshow')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_images', to='myapp.companysettings')),
            ],
            options={
                'verbose_name': 'Auth Page Image',
                'verbose_name_plural': 'Auth Page Images',
                'ordering': ['order'],
            },
        ),
    ]
