# Generated by Django 6.0 on 2026-01-24 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_authpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpageimage',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text='0.0 = Transparent (Image clear), 1.0 = Black (Image hidden). Default is 0.5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Overlay Opacity'),
        ),
    ]
