# Generated by Django 6.0 on 2026-01-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_tokenpackage_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='is_token_sale_active',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot buy token packages.', verbose_name='Enable Token Sales'),
        ),
    ]
