# Generated by Django 6.0 on 2026-01-28 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_companysettings_is_token_sale_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)')),
                ('billing_period', models.PositiveIntegerField(default=1, verbose_name='Billing Period (Count)')),
                ('billing_period_unit', models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('M', 'Months'), ('Y', 'Years')], default='M', max_length=1, verbose_name='Billing Period Unit')),
                ('tokens_per_period', models.PositiveIntegerField(help_text='Tokens granted each renewal', verbose_name='Tokens per Period')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('paypal_plan_id', models.CharField(blank=True, help_text='Optional: ID from PayPal Dashboard if needed', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('paypal_sub_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='PayPal Subscription ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
