# Generated by Django 6.0 on 2026-01-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='is_subscription_active',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot subscribe to plans.', verbose_name='Enable Subscriptions'),
        ),
    ]
