# Generated by Django 5.0 on 2024-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_companysettings_is_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='paypal_is_sandbox',
            field=models.BooleanField(default=True, help_text='If checked, payments will be processed in Sandbox (Test) mode. Uncheck for Live (Real Money).', verbose_name='PayPal Sandbox Mode'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='paypal_receiver_email',
            field=models.EmailField(blank=True, help_text='The email of the PayPal Business account that receives payments.', max_length=254, null=True, verbose_name='PayPal Receiver Email'),
        ),
    ]
