# Generated by Django 6.0 on 2026-01-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_companysettings_paypal_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='negative_prompt',
            field=models.TextField(blank=True, default='bad anatomy, bad hands, multiple views, abstract, signature, furry, anthro, 2koma, 4koma, comic, (text, watermark), logo, artist signature, patreon logo, patreon username, twitter username, blurred, unfocused, foggy, poorly drawn hands, bad quality, worst quality, worst detail,', help_text='NEGATIVE: Things you DO NOT want in the image.', null=True, verbose_name='Negative Prompt'),
        ),
    ]
