# Generated by Django 6.0 on 2026-02-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_character_negative_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokensettings',
            options={'verbose_name': 'Client Configuration', 'verbose_name_plural': 'Client Configuration'},
        ),
        migrations.AddField(
            model_name='tokensettings',
            name='allow_eye_detail_free',
            field=models.BooleanField(default=False, help_text='If checked, users without a subscription can use Eye Detailer.', verbose_name='Allow Eye Detailer (Free Tier)'),
        ),
        migrations.AddField(
            model_name='tokensettings',
            name='allow_face_detail_free',
            field=models.BooleanField(default=False, help_text='If checked, users without a subscription can use Face Detailer.', verbose_name='Allow Face Detailer (Free Tier)'),
        ),
        migrations.AddField(
            model_name='tokensettings',
            name='allow_upscale_free',
            field=models.BooleanField(default=False, help_text='If checked, users without a subscription can use Upscale.', verbose_name='Allow Upscale (Free Tier)'),
        ),
    ]
