# Generated by Django 6.0 on 2026-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_alter_tokensettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_eye_detail',
            field=models.BooleanField(default=False, help_text='Does this plan include Eye Detailer?', verbose_name='Allow Eye Detailer'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_face_detail',
            field=models.BooleanField(default=False, help_text='Does this plan include Face Detailer?', verbose_name='Allow Face Detailer'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_upscale',
            field=models.BooleanField(default=False, help_text='Does this plan include Upscale?', verbose_name='Allow Upscale'),
        ),
    ]
