# Generated by Django 6.0 on 2026-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_subscriptionplan_allow_eye_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features_list',
            field=models.TextField(blank=True, help_text="Enter features separated by commas (e.g., 'Priority Support, Cancel Anytime'). If empty, defaults will be used.", null=True, verbose_name='Custom Features List'),
        ),
    ]
