# Generated by Django 6.0 on 2026-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_subscriptionplan_features_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpackage',
            name='features_list',
            field=models.TextField(blank=True, help_text="Enter features separated by commas (e.g., 'Instant Delivery, Secure Payment'). If empty, defaults will be used.", null=True, verbose_name='Custom Features List'),
        ),
    ]
