# Generated by Django 6.0 on 2026-02-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_tokenpackage_features_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='How many days the premium features last. 0 = No time limit (or just tokens).', verbose_name='Duration (Days)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='unlock_eye_detail',
            field=models.BooleanField(default=False, help_text='Does this coupon unlock Eye Detailer?', verbose_name='Unlock Eye Detailer'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='unlock_face_detail',
            field=models.BooleanField(default=False, help_text='Does this coupon unlock Face Detailer?', verbose_name='Unlock Face Detailer'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='unlock_upscale',
            field=models.BooleanField(default=False, help_text='Does this coupon unlock Upscaler?', verbose_name='Unlock Upscaler'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Tokens to Grant'),
        ),
        migrations.CreateModel(
            name='UserPremiumGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(default='Premium Access', help_text='Reason for the grant', max_length=100)),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('grant_upscale', models.BooleanField(default=False)),
                ('grant_face_detail', models.BooleanField(default=False)),
                ('grant_eye_detail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, help_text='Source coupon (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Premium Grant',
                'verbose_name_plural': 'User Premium Grants',
            },
        ),
    ]
