# Generated by Django 6.0 on 2026-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_coupon_duration_days_coupon_unlock_eye_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Stripe, PayPal', max_length=50, verbose_name='Method Name')),
                ('config_key', models.CharField(help_text="Internal key (e.g., 'stripe', 'paypal'). DO NOT CHANGE once set.", max_length=50, unique=True, verbose_name='Config Key')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this payment method globally.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='Starts with pk_test_ or pk_live_', max_length=255, null=True, verbose_name='Stripe Publishable Key'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Starts with sk_test_ or sk_live_', max_length=255, null=True, verbose_name='Stripe Secret Key'),
        ),
    ]
