# Generated by Django 6.0 on 2026-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_paymentmethod_companysettings_stripe_publishable_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='privacy_content',
            field=models.TextField(blank=True, default='<p>Please add your Privacy Policy here.</p>', help_text='HTML content for Privacy Policy modal.', verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='terms_content',
            field=models.TextField(blank=True, default='<p>Please add your Terms & Conditions here.</p>', help_text='HTML content for Terms & Conditions modal.', verbose_name='Terms & Conditions'),
        ),
    ]
