# Generated by Django 6.0 on 2026-02-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_companysettings_privacy_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteraccesscode',
            name='limit_amount',
        ),
        migrations.RemoveField(
            model_name='characteraccesscode',
            name='reset_interval',
        ),
        migrations.RemoveField(
            model_name='usercharacteraccess',
            name='images_generated_current_period',
        ),
        migrations.RemoveField(
            model_name='usercharacteraccess',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='usercharacteraccess',
            name='limit_amount',
        ),
        migrations.RemoveField(
            model_name='usercharacteraccess',
            name='reset_interval',
        ),
    ]
