# Generated by Django 6.0 on 2026-02-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_remove_characteraccesscode_limit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='base_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='myapp.workflow'),
        ),
    ]
