# Generated by Django 6.0 on 2026-02-17 07:12

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_alter_character_base_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Video GPU 1', max_length=100)),
                ('base_url', models.CharField(help_text='Ex: http://127.0.0.1:8188', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Check this box to use this connection for VIDEO generation.')),
            ],
            options={
                'verbose_name': 'Video Connection Configuration',
                'verbose_name_plural': 'Video Connection Configurations',
            },
        ),
        migrations.CreateModel(
            name='VideoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json_file', models.FileField(upload_to='video_workflows/')),
                ('active_config', models.TextField(blank=True, help_text='Active JSON configuration for video generation.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to=myapp.models.video_output_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=3, help_text='Duration in seconds')),
                ('fps', models.IntegerField(default=24)),
                ('width', models.IntegerField(default=1024)),
                ('height', models.IntegerField(default=576)),
                ('seed', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to=settings.AUTH_USER_MODEL)),
                ('workflow_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.videoworkflow')),
            ],
        ),
    ]
