# Generated by Django 6.0 on 2026-02-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_videoconnectionconfig_videoworkflow_generatedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_type',
            field=models.CharField(choices=[('IMAGE', 'Image Generation'), ('VIDEO', 'Video Generation')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='generated_videos',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='myapp.generatedvideo'),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.character'),
        ),
    ]
