# Generated by Django 6.0 on 2026-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_chatmessage_chat_type_chatmessage_generated_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='Ex: 3, 5, 9', unique=True, verbose_name='Duration (seconds)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video Duration Option',
                'verbose_name_plural': 'Video Duration Options',
                'ordering': ['duration'],
            },
        ),
        migrations.CreateModel(
            name='VideoResolutionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: SD, HD, FHD', max_length=50, verbose_name='Label')),
                ('width', models.PositiveIntegerField(default=1024)),
                ('height', models.PositiveIntegerField(default=576)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video Resolution Option',
                'verbose_name_plural': 'Video Resolution Options',
            },
        ),
    ]
