# Generated by Django 6.0 on 2026-02-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_videodurationoption_videoresolutionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Video Configuration',
                'verbose_name_plural': 'Video Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='videodurationoption',
            options={'ordering': ['duration'], 'verbose_name': 'Duration Option', 'verbose_name_plural': 'Duration Options'},
        ),
        migrations.AlterModelOptions(
            name='videoresolutionoption',
            options={'verbose_name': 'Resolution Option', 'verbose_name_plural': 'Resolution Options'},
        ),
        migrations.AlterField(
            model_name='videodurationoption',
            name='duration',
            field=models.PositiveIntegerField(help_text='Ex: 3, 5, 9', verbose_name='Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='videodurationoption',
            name='config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='myapp.videoconfiguration'),
        ),
        migrations.AddField(
            model_name='videoresolutionoption',
            name='config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='myapp.videoconfiguration'),
        ),
    ]
