# Generated by Django 6.0 on 2026-02-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_videoconfiguration_alter_videodurationoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQualityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: High, Medium, Low', max_length=50, verbose_name='Label')),
                ('value', models.PositiveIntegerField(default=25, help_text='Value to send to the workflow (e.g. steps)', verbose_name='Quality Value')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='myapp.videoconfiguration')),
            ],
            options={
                'verbose_name': 'Quality Option',
                'verbose_name_plural': 'Quality Options',
            },
        ),
        migrations.DeleteModel(
            name='VideoResolutionOption',
        ),
    ]
