# Generated by Django 6.0 on 2026-02-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_videoqualityoption_delete_videoresolutionoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='negative_prompt',
        ),
        migrations.RemoveField(
            model_name='character',
            name='prompt_prefix',
        ),
        migrations.RemoveField(
            model_name='character',
            name='prompt_suffix',
        ),
    ]
