# Generated by Django 6.0 on 2026-02-23 17:18

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_remove_character_negative_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='generation_workflow',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.video_generation_workflow_path, verbose_name='Generation Workflow (JSON)'),
        ),
    ]
