# Generated by Django 6.0 on 2026-02-24 14:33

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_generatedvideo_generation_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.video_output_path),
        ),
    ]
