# Generated by Django 6.0 on 2026-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_generatedvideo_error_message_generatedvideo_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedvideo',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='task_id',
        ),
        migrations.AddField(
            model_name='characterimage',
            name='is_hidden_from_admin',
            field=models.BooleanField(default=False, help_text='If true, this image is hidden from the admin list and public gallery.', verbose_name='Hidden (Private Mode)'),
        ),
    ]
