# Generated by Django 6.0 on 2026-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_generatedvideo_generation_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='is_hidden_from_admin',
            field=models.BooleanField(default=False, help_text='If true, this image is hidden from the admin list and public gallery.', verbose_name='Hidden (Private Mode)'),
        ),
    ]
