# Generated by Django 6.0 on 2026-03-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_remove_generatedvideo_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCharacterImage',
            fields=[
            ],
            options={
                'verbose_name': 'Private Image (Hidden)',
                'verbose_name_plural': 'Private Images (Hidden)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.characterimage',),
        ),
    ]
