# Generated by Django 6.0 on 2026-03-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_privatecharacterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='crypto_min_confirmations',
            field=models.PositiveIntegerField(default=10, help_text='Minimum blocks to confirm payment.', verbose_name='Min Confirmations'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='crypto_trongrid_api_key',
            field=models.CharField(blank=True, help_text='TronGrid Pro API Key', max_length=100, null=True, verbose_name='TronGrid API Key'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='crypto_usdt_address',
            field=models.CharField(blank=True, help_text='Your TRC20 Wallet Address (e.g. TQ5b...)', max_length=100, null=True, verbose_name='USDT TRC20 Address'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Unique exact amount for Crypto payment (e.g. 5.001234)', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='crypto_tx_id',
            field=models.CharField(blank=True, help_text='Blockchain Transaction ID', max_length=100, null=True),
        ),
    ]
