# Generated by Django 6.0 on 2026-03-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_companysettings_crypto_min_confirmations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoGuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crypto_guide/', verbose_name='Guide Image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Caption (Optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the slider')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_guide_images', to='myapp.companysettings')),
            ],
            options={
                'verbose_name': 'Crypto Guide Image',
                'verbose_name_plural': 'Crypto Guide Images',
                'ordering': ['order'],
            },
        ),
    ]
