# Generated by Django 6.0 on 2026-03-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_cryptoguideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='crypto_usdt_qr',
            field=models.ImageField(blank=True, help_text='Upload the QR code image for your wallet.', null=True, upload_to='company_logos/', verbose_name='USDT Wallet QR Code'),
        ),
    ]
