# Generated by Django 5.2.9 on 2026-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_companysettings_crypto_usdt_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='is_image_generation_enabled',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot generate images in the workspace.', verbose_name='Enable Image Generation'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='is_video_generation_enabled',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot generate videos in the workspace.', verbose_name='Enable Video Generation'),
        ),
    ]
