# Generated by Django 5.2.9 on 2026-04-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_companysettings_is_image_generation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showcase/', verbose_name='Showcase Image')),
                ('prompt', models.TextField(help_text='The text that will be typed out.', verbose_name='Prompt')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the showcase')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='myapp.companysettings')),
            ],
            options={
                'verbose_name': 'Showcase Item',
                'verbose_name_plural': 'Showcase Items',
                'ordering': ['order'],
            },
        ),
    ]
