# Generated by Django 5.2.13 on 2026-05-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_showcaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enable_blacklist',
            field=models.BooleanField(default=True, verbose_name='Enable Blacklist Filter'),
        ),
        migrations.AddField(
            model_name='character',
            name='promp_character',
            field=models.TextField(blank=True, null=True, verbose_name='Character Prompt (Node 17)'),
        ),
        migrations.AddField(
            model_name='character',
            name='quality_amateur',
            field=models.TextField(blank=True, null=True, verbose_name='Amateur Text (Node 33)'),
        ),
        migrations.AddField(
            model_name='character',
            name='quality_professional',
            field=models.TextField(blank=True, null=True, verbose_name='Professional Text (Node 33)'),
        ),
        migrations.AddField(
            model_name='character',
            name='quality_standar',
            field=models.TextField(blank=True, null=True, verbose_name='Standar Text (Node 33)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactercategory'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactersubcategory'),
        ),
    ]
