# Generated by Django 6.0 on 2026-05-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_character_enable_blacklist_character_promp_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='promp_character',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quality_amateur',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quality_professional',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quality_standar',
        ),
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.ForeignKey(help_text='Mandatory: The main classification (e.g., Realistic, Anime).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactercategory'),
        ),
        migrations.AlterField(
            model_name='character',
            name='enable_blacklist',
            field=models.BooleanField(default=False, help_text='Enable a global negative prompt (blacklist) for this character.', verbose_name='Enable Blacklist'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, this character will be hidden from the workspace.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, this character will NOT appear in the public list. Users need a code to access it.', verbose_name='Private Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional: A specific sub-classification (e.g., Cyberpunk, Fantasy). Only one allowed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='myapp.charactersubcategory'),
        ),
    ]
